# Overrides for any parameter below
overrides:
    threads                : 12

# Format below is:
# Benchmark Suite
#     |
#     --- Benchmark
#           |
#           --- Sub-benchmark
#                 |
#                 --- Info like the path and executable
#                 --- Parameters for the executable
tailbench:
    img-dnn-integrated:
        info:
            path         : "./benchmarks/tailbench/img-dnn"
            executable   : "run_integrated.sh"
        parameters:
            threads      : 1
            reqs         : 100000000
            warmup_reqs  : 5000
            max_reqs     : 10000
            qps          : 500
            min_sleep_ns : 10000
    img-dnn-networked:
        info:
            path         : "./benchmarks/tailbench/img-dnn"
            executable   : "run_networked.sh"
        parameters:
            threads      : 1
            reqs         : 100000000
            warmup_reqs  : 5000
            max_reqs     : 10000
            qps          : 500
            data_dir     : "../data/img-dnn/mnist"
    masstree-integrated:
        info:
            path         : "./benchmarks/tailbench/masstree"
            executable   : "run_integrated.sh"
        parameters:
            threads      : 1
            warmup_reqs  : 14000
            max_reqs     : 100000
            qps          : 1000
            min_sleep_ns : 10000
    moses-integrated:
        info:
            path         : "./benchmarks/tailbench/moses"
            executable   : "run_integrated.sh"
        parameters:
            threads      : 1
            warmup_reqs  : 500
            max_reqs     : 500
            qps          : 100
            min_sleep_ns : 10000
            num_tasks    : 100000
            verbose      : 0
    moses-networked:
        info:
            path         : "./benchmarks/tailbench/moses"
            executable   : "run_networked.sh"
        parameters:
            threads      : 1
            warmup_reqs  : 500
            max_reqs     : 500
            qps          : 100
            num_tasks    : 100000
            verbose      : 0
    silo-integrated:
        info:
            path         : "./benchmarks/tailbench/silo"
            executable   : "run_integrated.sh"
        parameters:
            threads        : 1
            warehouses     : 1
            ops_per_worker : 10000000
            warmup_reqs    : 20000
            max_reqs       : 100000
            qps            : 2000
            min_sleep_ns   : 10000
    silo-networked:
        info:
            path         : "./benchmarks/tailbench/silo"
            executable   : "run_networked.sh"
        parameters:
            threads        : 1
            warehouses     : 1
            ops_per_worker : 10000000
            warmup_reqs    : 20000
            max_reqs       : 100000
            qps            : 2000
            min_sleep_ns   : 10000
    specjbb-integrated:
        info:
            path         : "./benchmarks/tailbench/specjbb"
            executable   : "run_integrated.sh"
        parameters:
            threads      : 1
            warehouses   : 1
            warmup_reqs  : 25000
            max_reqs     : 25000
            qps          : 2000
            min_sleep_ns : 10000
    specjbb-networked:
        info:
            path         : "./benchmarks/tailbench/specjbb"
            executable   : "run_networked.sh"
        parameters:
            threads        : 1
            warehouses     : 1
            warmup_reqs    : 25000
            max_reqs       : 25000
            qps            : 5000
            min_sleep_ns   : 10000
    sphinx-integrated:
        info:
            path         : "./benchmarks/tailbench/sphinx"
            executable   : "run_integrated.sh"
        parameters:
            threads      : 1
            warmup_reqs  : 10
            max_reqs     : 10
            qps          : 500
            min_sleep_ns : 10000
    sphinx-networked:
        info:
            path         : "./benchmarks/tailbench/sphinx"
            executable   : "run_networked.sh"
        parameters:
            threads      : 1
            warmup_reqs  : 10
            max_reqs     : 10
            qps          : 500
            min_sleep_ns : 10000

ycsb:
    workloada:
        info:
            path         : "./benchmarks/ycsb"
            executable   : "bin/ycsb"
        parameters:
            workload                 : "site.ycsb.workloads.CoreWorkload"
            readallfields            : "true"
            readproportion           : 0.5
            updateproportion         : 0.5
            scanproportion           : 0
            insertproportion         : 0
            recordcountload          : 4000000
            operationcountload       : 15000000
            recordcountrun           : 1000000
            operationcountrun        : 7500000
            fieldcount               : 10
            fieldlength              : 500
            requestdistribution      : "uniform"
            insertorder              : "hashed"
            maxscanlength            : 1000
            scanlengthdistribution   : "uniform"
            hdrhistogram.percentiles : "50,75,90,95,99,99.9,99.99"
            threadcount              : 12
            database                 : "redis"
            redis-server             : "redis.host=127.0.0.1"
    workloadb:
        info:
            path         : "./benchmarks/ycsb"
            executable   : "bin/ycsb"
        parameters:
            workload                 : "site.ycsb.workloads.CoreWorkload"
            readallfields            : "true"
            readproportion           : 0.95
            updateproportion         : 0.05
            scanproportion           : 0
            insertproportion         : 0
            recordcountload          : 3250000
            operationcountload       : 15000000
            recordcountrun           : 1000000
            operationcountrun        : 7500000
            fieldcount               : 10
            fieldlength              : 500
            requestdistribution      : "uniform"
            insertorder              : "hashed"
            maxscanlength            : 1000
            scanlengthdistribution   : "uniform"
            hdrhistogram.percentiles : "50,75,90,95,99,99.9,99.99"
            threadcount              : 12
            database                 : "redis"
            redis-server             : "redis.host=127.0.0.1"
    workloadc:
        info:
            path         : "./benchmarks/ycsb"
            executable   : "bin/ycsb"
        parameters:
            workload                 : "site.ycsb.workloads.CoreWorkload"
            readallfields            : "true"
            readproportion           : 1
            updateproportion         : 0
            scanproportion           : 0
            insertproportion         : 0
            recordcountload          : 3250000
            operationcountload       : 15000000
            recordcountrun           : 1000000
            operationcountrun        : 7500000
            fieldcount               : 10
            fieldlength              : 500
            requestdistribution      : "uniform"
            insertorder              : "hashed"
            maxscanlength            : 1000
            scanlengthdistribution   : "uniform"
            hdrhistogram.percentiles : "50,75,90,95,99,99.9,99.99"
            threadcount              : 12
            database                 : "redis"
            redis-server             : "redis.host=127.0.0.1"
    workloadf:
        info:
            path         : "./benchmarks/ycsb"
            executable   : "bin/ycsb"
        parameters:
            workload                  : "site.ycsb.workloads.CoreWorkload"
            readallfields             : "true"
            readproportion            : 0.5
            updateproportion          : 0
            scanproportion            : 0
            insertproportion          : 0
            readmodifywriteproportion : 0.5
            recordcountload           : 3250000
            operationcountload        : 15000000
            recordcountrun            : 1000000
            operationcountrun         : 7500000
            fieldcount                : 10
            fieldlength               : 500
            requestdistribution       : "uniform"
            insertorder               : "hashed"
            maxscanlength             : 1000
            scanlengthdistribution    : "uniform"
            hdrhistogram.percentiles  : "50,75,90,95,99,99.9,99.99"
            threadcount               : 12
            database                  : "redis"
            redis-server              : "redis.host=127.0.0.1"
    workloadd:
        info:
            path         : "./benchmarks/ycsb"
            executable   : "bin/ycsb"
        parameters:
            workload                 : "site.ycsb.workloads.CoreWorkload"
            readallfields            : "true"
            readproportion           : 0.95
            updateproportion         : 0
            scanproportion           : 0
            insertproportion         : 0.05
            recordcountload          : 3250000
            operationcountload       : 15000000
            recordcountrun           : 1000000
            operationcountrun        : 7500000
            fieldcount               : 10
            fieldlength              : 500
            requestdistribution      : "uniform"
            insertorder              : "hashed"
            maxscanlength            : 1000
            scanlengthdistribution   : "uniform"
            hdrhistogram.percentiles : "50,75,90,95,99,99.9,99.99"
            threadcount              : 12
            database                 : "redis"
            redis-server             : "redis.host=127.0.0.1"

# Parameters 'requests' and 'test-time' are mutually exclusive
memtier:
    memtier:
        info:
            path         : "./benchmarks/memtier"
            executable   : "memtier_benchmark"
        parameters:
            pipeline             : 11
            clients              : 20
            threads              : 1
            data-size            : 500
            # requests             : 5000000
            key-maximum          : 75000000
            key-pattern          : "G:G"
            ratio                : "1:1"
            distinct-client-seed : "true"
            randomize            : "true"
            run-count            : 1
            key-stddev           : 5125000
            print-percentiles    : "50,75,90,95,99,99.9,99.99,100"
            test-time            : 120

pmbench:
    pmbench:
        info:
            path         : "./benchmarks/pmbench"
            executable   : "pmbench"
        parameters:
            mapsize : 22000
            setsize : 22000
            threads : 10
            time    : 150

# cachebench:
#     cachebench:
#         info:
#             path         : "./benchmarks/cachebench/opt/cachelib/bin"
#             executable   : "cachebench"
#         parameters:
#             json_test_config : "config.json"
#             timeout_seconds  : 240
#             progress         : "true"
