# Experiment definitiosn below containing general information on what operations to do
numa_mode_compare:
    paths:
        output-directory       : "numa_mode_compare" # If not inputted, default directory is experiment name
    operations:
        # - execute
        # - process
        - analyze
    numa-node-configs:                   # Used to set up different numa locality configurations
        small-cpu-node         : 1       # NUMA node with low memory capacity
        small-mem-node         : 1       # NUMA node with low memory capacity
        big-cpu-node           : 0       # NUMA node with high memory capacity
        big-mem-node           : 0       # NUMA node with high memory capacity
    numa-mem-configs:
        - local                          # All memory allocated on the same memory and CPU NUMA node
        - remote                         # All memory allocated on different CPU and memory NUMA nodes
        - both                           # Memory allocated first on same small CPU node, then on big mem node
    general-analysis-metrics:            # General metrics to plot (look at produced json file for metric names)
        - "C-States_LLCRDMISSLAT"
    suites:                              # Benchmarks to run
        tailbench:
            benchmarks:
                # - img-dnn-integrated
                # - img-dnn-networked
                # - masstree-integrated
                # - moses-integrated
                # - moses-networked
                # - silo-integrated
                # - silo-networked
                # - specjbb-integrated
                # - specjbb-networked
                # - sphinx-integrated
                # - sphinx-networked
            specific-metrics:
                # - "throughput"
        ycsb:
            benchmarks:
                - workloada
                - workloadb
                - workloadc
                - workloadf
                - workloadd
            specific-metrics:
                - "INSERT_99.99PercentileLatency(us)"
        memtier:
            benchmarks:
                # - memtier
            specific-metrics:
                # - "throughput"
        pmbench:
            benchmarks:
                - pmbench
            specific-metrics:
                # - "throughput"
        cachebench:
            benchmarks:
                # - cachebench
            specific-metrics:
                # - "throughput"
        gapbs:
            benchmarks:
                # - gapbs
            specific-metrics:
                # - "throughput"
