# Experiment definitiosn below containing general information on what operations to do
numa_mode_compare:
    paths:
        output-directory       : "numa_mode_compare" # If this path is not there, default directory is experiment name
    operations:
        # - execute
        - process
        # - analyze
    numa-node-configs:                   # Used to set up different numa locality configurations
        small-cpu-node         : 1       # NUMA node with low memory capacity
        small-mem-node         : 1       # NUMA node with low memory capacity
        big-cpu-node           : 0       # NUMA node with high memory capacity
        big-mem-node           : 0       # NUMA node with high memory capacity
    numa-mem-configs:
        - local                          # All memory allocated on the same memory and CPU NUMA node
        - remote                         # All memory allocated on different CPU and memory NUMA nodes
        - both                           # Memory allocated first on same small CPU NUMA node, then on big memory node
    benchmarks:                          # Benchmarks to run
        tailbench:
            # - img-dnn-integrated
            # - img-dnn-networked
            # - masstree-integrated
            # - moses-integrated
            # - moses-networked
            # - silo-integrated
            # - silo-networked
            # - specjbb-integrated
            # - specjbb-networked
            # - sphinx-integrated
            # - sphinx-networked
        ycsb:
            - workloada
            - workloadb
            - workloadc
            - workloadf
            - workloadd
        memtier:
            # - memtier
        pmbench:
            - pmbench
        cachebench:
            # - cachebench
        gapbs:
            # - gapbs
