# General info for all benchmarks
# "exe-prefixes" are the statements before commands to typically capture performance results
#     like Intel's pcm or vtune, or AMD's uprof
#     NOTE: Using multiple performance monitors can cause issues since they may use the same
#          performance counters. Also, both vtune and uprof are not installed by this repo
#          and may need to be adjusted to get the correct executable path
# "numa-config" contains info for the defaulted NUMA nodes (remote is meant to contain far
#     less memory than local).
script-settings:
    status-update-interval : 30     # Time to wait before updating user when running benchmarks (1sec for polling)
    samples                : 2      # Number of times to run and average each benchmark (managed in benchmark class)
exe-prefixes:
    # vtune                  : "sudo /opt/intel/oneapi/vtune/2022.1.0/bin64/vtune -collect performance-snapshot "
    # uprof                  : "sudo /opt/AMDuProf_3.5-671/bin/AMDuProfCLI collect -o ./uprof-out "
    pcm                    : "sudo pcm -csv=temp-pcm.csv --external_program"
    pcm-memory             : "sudo pcm-memory -csv=temp-pcm-memory.csv --external_program"
    numa                   : "sudo numactl --cpunodebind=0 --membind=0" # Overwrite nodes if desired in experiments.execute(...)
execution:
paths:
    script-root            : "Null" # Overwritten in script for current working directory
    redis-directory        : "tools/redis/src"
    results-directory      : "results"
experiments:                        # List of experiments to run
  - numa_mode_compare
